# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='ip')),
                ('port', models.SmallIntegerField(verbose_name='port')),
                ('protocol', models.CharField(default='HTTP', max_length=7, verbose_name='代理类型')),
                ('address', models.CharField(default='', max_length=30, verbose_name='归宿地')),
                ('anonymous', models.BooleanField(default=1, verbose_name='是否匿名')),
                ('abroad', models.BooleanField(default=0, verbose_name='是否是国外ip')),
                ('available', models.SmallIntegerField(default=3, verbose_name='可用性')),
            ],
            options={
                'verbose_name': '代理',
                'verbose_name_plural': '代理池',
            },
        ),
        migrations.AlterUniqueTogether(
            name='proxypool',
            unique_together=set([('ip', 'port')]),
        ),
    ]
