# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxyPool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='网站名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('website', models.URLField(verbose_name='网址')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
            },
        ),
    ]
