# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proxyPool', '0004_auto_20180111_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxypool',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
